// Shows readiness progress, score breakdown, alert settings and recent learning activity.
import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { COLORS } from '../constants/theme';
import AppHeader from '../components/AppHeader';
import SemicircleProgress from '../components/SemicircleProgress';
import { calculateReadinessBreakdown, getProfileTier, getReadinessSummary } from '../utils/guideUtils';

// Displays readiness progress, learning statistics and alert preferences.
export default function ProfileScreen({ profile, guides, notificationPrefs, onEnableNotifications, onUpdateNotificationPrefs, syncStatus }) {
  const breakdown=useMemo(()=>calculateReadinessBreakdown(profile.guideProgress||{},guides),[profile.guideProgress,guides]);
  const teamGuides=useMemo(()=>guides.filter(g=>g.category==='team'),[guides]);
  const completedTeam=teamGuides.filter(g=>profile.guideProgress?.[g.id]?.score>=profile.guideProgress?.[g.id]?.totalQuestions).length;
  const completedAny=Object.keys(profile.guideProgress||{}).length;
  const avgScore=completedAny?Math.round(Object.values(profile.guideProgress||{}).reduce((sum,x)=>sum+((x.score||0)/Math.max(x.totalQuestions||1,1)),0)/completedAny*100):0;
  const tier=getProfileTier(profile.readinessPercent); const summary=getReadinessSummary(profile.readinessPercent);
  const prefs=notificationPrefs||{};
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}>
    <AppHeader/><View style={styles.heroCard}><SemicircleProgress value={profile.readinessPercent} points={profile.readinessPoints} delta={profile.lastEarnedPoints||0} label={tier}/><Text style={styles.heroTitle}>Disaster readiness</Text><Text style={styles.heroSubtitle}>{summary}</Text></View>
    <View style={styles.statsGrid}><Stat n={`${breakdown.teamMastery}%`} l="Team guide mastery"/><Stat n={`${breakdown.communityLearning}%`} l="Community learning"/><Stat n={`${breakdown.coveredTypeCount}/${breakdown.totalTypeCount}`} l="Hazard coverage"/><Stat n={`${avgScore}%`} l="Average quiz score"/></View>
    <View style={styles.sectionCard}><Text style={styles.sectionTitle}>How Readis calculates readiness</Text><Rule w="45%" t="Trusted team-guide quiz performance carries the most weight because it is the most reliable preparedness signal."/><Rule w="20%" t="Community-guide learning adds extra readiness when you learn from practical tips shared by others."/><Rule w="20%" t="Coverage rewards learning across different disaster types, not only one topic."/><Rule w="15%" t="Readiness points show momentum from quizzes you completed well."/></View>

    <View style={styles.sectionCard}><View style={styles.notificationHeader}><View style={{flex:1}}><Text style={styles.sectionTitle}>Alerts and live updates</Text><Text style={styles.sectionText}>Choose when Readis may notify you. Permissions are requested only after you enable alerts.</Text></View><Ionicons name="notifications-outline" size={26} color={COLORS.primary}/></View>
      {!prefs.enabled?<Pressable style={styles.enableButton} onPress={onEnableNotifications}><Ionicons name="notifications" size={18} color="#FFF"/><Text style={styles.enableText}>Enable notifications</Text></Pressable>:<Text style={styles.enabledText}><Ionicons name="checkmark-circle" size={16} color="#168A5B"/> Notifications enabled</Text>}
      <ToggleRow label="Nearby incident alerts" value={Boolean(prefs.nearbyIncidents)} disabled={!prefs.enabled} onValueChange={v=>onUpdateNotificationPrefs?.({...prefs,nearbyIncidents:v})}/>
      <ToggleRow label="New guide alerts" value={Boolean(prefs.newGuides)} disabled={!prefs.enabled} onValueChange={v=>onUpdateNotificationPrefs?.({...prefs,newGuides:v})}/>
      <Text style={styles.radiusLabel}>Nearby radius</Text><View style={styles.radiusRow}>{[1,3,5].map(r=><Pressable key={r} disabled={!prefs.enabled} onPress={()=>onUpdateNotificationPrefs?.({...prefs,radiusKm:r})} style={[styles.radiusPill,prefs.radiusKm===r&&styles.radiusActive,!prefs.enabled&&{opacity:.45}]}><Text style={[styles.radiusText,prefs.radiusKm===r&&styles.radiusTextActive]}>{r} km</Text></Pressable>)}</View>
      <Text style={styles.syncText}>{syncStatus?.configured?'Live community API connected while the app is open.':'Local mode. Set EXPO_PUBLIC_READIS_API_URL to enable cross-device live synchronisation.'}</Text>
    </View>

    <View style={styles.statsGrid}><Stat light n={`${completedTeam}/${teamGuides.length}`} l="Team guides completed fully"/><Stat light n={completedAny} l="Guides attempted"/></View>
    <View style={styles.sectionCard}><Text style={styles.sectionTitle}>Recent readiness activity</Text>{!completedAny?<Text style={styles.sectionText}>Read a guide and complete the quiz to start building your readiness profile.</Text>:Object.entries(profile.guideProgress||{}).sort((a,b)=>(b[1]?.updatedAt||0)-(a[1]?.updatedAt||0)).slice(0,5).map(([id,p])=><View key={id} style={styles.progressItem}><View style={{flex:1}}><Text style={styles.progressTitle}>{p.title}</Text><Text style={styles.progressMeta}>Score {p.score}/{p.totalQuestions}</Text></View><Text style={styles.progressPoints}>+{p.pointsEarned}</Text></View>)}</View>
  </ScrollView>;
}
// Displays one small readiness statistic card.
const Stat=({n,l,light})=><View style={light?styles.statCardLight:styles.statCard}><Text style={styles.statNumber}>{n}</Text><Text style={styles.statLabel}>{l}</Text></View>;
// Displays one weighted rule used in the readiness score.
const Rule=({w,t})=><View style={styles.ruleRow}><Text style={styles.ruleWeight}>{w}</Text><Text style={styles.ruleText}>{t}</Text></View>;
// Displays one labelled switch for a notification preference.
const ToggleRow=({label,value,onValueChange,disabled})=><View style={styles.toggleRow}><Text style={styles.toggleLabel}>{label}</Text><Switch value={value} onValueChange={onValueChange} disabled={disabled} trackColor={{true:COLORS.primarySoft}} thumbColor={value?COLORS.primary:'#F4F4F4'}/></View>;
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F4F7FC'},content:{padding:20,paddingBottom:120},heroCard:{marginTop:10,backgroundColor:'#FFF',borderRadius:28,paddingVertical:24,paddingHorizontal:18,alignItems:'center',shadowColor:'#19305A',shadowOpacity:.06,shadowRadius:12,shadowOffset:{width:0,height:8},elevation:3},heroTitle:{marginTop:18,fontSize:28,fontWeight:'900',color:'#060B28'},heroSubtitle:{marginTop:8,textAlign:'center',color:COLORS.textMuted,lineHeight:22,fontSize:15,paddingHorizontal:10},statsGrid:{marginTop:18,flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:12},statCard:{width:'48%',backgroundColor:'#EEF4FF',borderRadius:18,padding:16},statCardLight:{width:'48%',backgroundColor:'#FFF',borderRadius:18,padding:16,borderWidth:1,borderColor:COLORS.border},statNumber:{color:COLORS.primary,fontSize:24,fontWeight:'900'},statLabel:{marginTop:6,color:COLORS.textMuted,lineHeight:20},sectionCard:{marginTop:16,backgroundColor:'#FFF',borderRadius:18,padding:16,borderWidth:1,borderColor:COLORS.border},sectionTitle:{fontSize:18,fontWeight:'800',color:COLORS.text,marginBottom:10},sectionText:{color:COLORS.textMuted,lineHeight:22,fontSize:15},ruleRow:{flexDirection:'row',alignItems:'flex-start',gap:12,paddingVertical:8},ruleWeight:{width:42,color:COLORS.primary,fontSize:16,fontWeight:'900'},ruleText:{flex:1,color:COLORS.textMuted,lineHeight:22},progressItem:{paddingVertical:12,borderTopWidth:1,borderTopColor:COLORS.border,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},progressTitle:{color:COLORS.text,fontWeight:'700'},progressMeta:{color:COLORS.textMuted,marginTop:4},progressPoints:{color:COLORS.primary,fontWeight:'800',fontSize:18},notificationHeader:{flexDirection:'row',gap:12,alignItems:'flex-start'},enableButton:{marginTop:8,backgroundColor:COLORS.primary,borderRadius:14,paddingVertical:12,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},enableText:{color:'#FFF',fontWeight:'800'},enabledText:{color:'#168A5B',fontWeight:'700',marginVertical:8},toggleRow:{paddingVertical:11,borderTopWidth:1,borderTopColor:COLORS.border,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},toggleLabel:{color:COLORS.text,fontWeight:'600'},radiusLabel:{marginTop:12,color:COLORS.textMuted,fontWeight:'700'},radiusRow:{flexDirection:'row',gap:8,marginTop:8},radiusPill:{borderWidth:1,borderColor:COLORS.border,borderRadius:999,paddingHorizontal:13,paddingVertical:8},radiusActive:{backgroundColor:COLORS.primary,borderColor:COLORS.primary},radiusText:{color:COLORS.text,fontWeight:'700'},radiusTextActive:{color:'#FFF'},syncText:{marginTop:12,color:COLORS.textMuted,fontSize:12,lineHeight:18}});
